"""
agentic_rag/rule_generator.py
─────────────────────────────
Automated firewall rule synthesis engine for Agentic RAG.
Converts threat reasoning decisions into production-ready FirewallRule dictionaries
compatible with Member 1's RuleEngine.
"""

from __future__ import annotations

import hashlib
import logging
import time
from typing import Any, Dict, List, Optional

from agentic_rag.threat_reasoner import ReasoningDecision

logger = logging.getLogger(__name__)


class RuleGenerator:
    """
    Synthesizes actionable firewall filtering rules from threat decisions.
    """

    def __init__(self, default_priority: int = 25) -> None:
        self.default_priority = default_priority

    def generate_rules(
        self,
        flow: dict[str, Any],
        decision: ReasoningDecision,
    ) -> list[dict[str, Any]]:
        """
        Produces one or more firewall rule dictionaries based on the decision.
        """
        # If the action is alert or allow, do not generate active blocking rules
        if decision.recommended_action not in ("block", "drop"):
            return []

        src_ip = str(flow.get("src_ip", "0.0.0.0"))
        dst_port = flow.get("dst_port")
        proto = str(flow.get("protocol", "any")).lower()

        # Build stable rule hash
        seed = f"{src_ip}_{dst_port}_{proto}_{decision.threat_name}_{int(time.time() // 60)}"
        rule_hash = hashlib.sha256(seed.encode()).hexdigest()[:8]
        rule_id = f"rag_rule_{rule_hash}"

        # Determine priority: critical threats get higher evaluation priority (lower numeric value)
        priority = self.default_priority
        if decision.severity == "CRITICAL":
            priority = 15
        elif decision.severity == "HIGH":
            priority = 20
        elif decision.severity == "MEDIUM":
            priority = 35

        cve_str = f" [{', '.join(decision.matched_cves)}]" if decision.matched_cves else ""
        desc = (
            f"Auto-generated by Agentic RAG: {decision.threat_name}{cve_str}. "
            f"Confidence: {decision.confidence:.2f}."
        )

        rule_dict: dict[str, Any] = {
            "rule_id": rule_id,
            "priority": priority,
            "action": decision.recommended_action,
            "src_ip": src_ip,
            "dst_ip": "any",
            "src_port": None,
            "dst_port": dst_port,
            "protocol": proto if proto in ("tcp", "udp", "icmp") else None,
            "tcp_flags": None,
            "description": desc,
            "created_by": "rag_agent",
            "enabled": True,
        }

        # For volumetric DoS / SYN flood, drop all traffic from offending source IP
        if decision.threat_category == "DoS":
            rule_dict["dst_port"] = None  # Block across all ports
            rule_dict["action"] = "drop"

        logger.info(f"Synthesized dynamic firewall rule '{rule_id}' ({rule_dict['action'].upper()} {src_ip}).")
        return [rule_dict]
