"""
simulation/node_simulator.py
────────────────────────────
Simulates a complete, autonomous Edge Firewall Node in an enterprise environment:
1. Ingests packet streams from benign, attack, or anomaly generators.
2. Evaluates packets through the FirewallController + trained Deep RL model.
3. Automatically triggers Agentic RAG when zero-day anomalies occur.
4. Generates real-time detection telemetry and exports trained model weights
   for Member 3's Federated Learning aggregation rounds.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from firewall.firewall_controller import FirewallController, FirewallMetrics
from firewall.rule_engine import FirewallRule, RuleAction
from rl_agent.checkpoint import CheckpointManager
from rl_agent.models.dqn import DuelingDQN
from simulation.anomaly_generator import AnomalyTrafficGenerator
from simulation.attack_generator import AttackTrafficGenerator
from simulation.benign_traffic import BenignTrafficGenerator

logger = logging.getLogger(__name__)


@dataclass
class NodeSimulationReport:
    node_id: str
    total_packets: int
    allowed_count: int
    blocked_count: int
    dropped_count: int
    rag_triggers: int
    emergency_drops: int
    true_positives: int
    false_positives: int
    true_negatives: int
    false_negatives: int
    accuracy: float
    precision: float
    recall: float
    f1_score: float
    duration_seconds: float
    packets_per_second: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "node_id": self.node_id,
            "total_packets": self.total_packets,
            "allowed_count": self.allowed_count,
            "blocked_count": self.blocked_count,
            "dropped_count": self.dropped_count,
            "rag_triggers": self.rag_triggers,
            "emergency_drops": self.emergency_drops,
            "accuracy": round(self.accuracy, 4),
            "precision": round(self.precision, 4),
            "recall": round(self.recall, 4),
            "f1_score": round(self.f1_score, 4),
            "duration_seconds": round(self.duration_seconds, 2),
            "packets_per_second": round(self.packets_per_second, 1),
        }


class EdgeNodeSimulator:
    """
    Simulates a standalone Edge Firewall node under active network load.
    """

    def __init__(
        self,
        node_id: str = "edge_node_01",
        config_path: str = "./config/firewall.yaml",
        model_path: Optional[str] = "./rl_agent/models/checkpoints/best_model.pt",
        target_ip: str = "192.168.1.100",
    ) -> None:
        self.node_id = node_id
        self.target_ip = target_ip
        self.controller = FirewallController(config_path=config_path)

        # Load trained RL model if present
        if model_path and Path(model_path).exists():
            try:
                model = DuelingDQN()
                CheckpointManager().load(model, model_path)
                self.controller.classifier.set_rl_model(model)
                logger.info(f"Loaded trained RL model for {node_id}")
            except Exception as e:
                logger.warning(f"Could not load RL model: {e}")

        # Default mock RAG handler representing Member 2's response
        self._dynamic_rules_added = 0
        self.controller.register_rag_hook(self._default_rag_handler)

    def _default_rag_handler(self, flow_features: dict[str, Any], anomaly_score: float) -> dict[str, Any]:
        """Simulates Member 2's Agentic RAG analysis and dynamic rule response."""
        self._dynamic_rules_added += 1
        rule_id = f"RAG-{self.node_id}-{self._dynamic_rules_added:03d}"

        # Member 2 contract return dictionary
        return {
            "threat_type": "anomalous_zero_day_probe",
            "confidence": 0.95,
            "rules": [
                {
                    "rule_id": rule_id,
                    "priority": 15,
                    "action": "block",
                    "src_ip": flow_features.get("src_ip"),
                    "dst_port": flow_features.get("dst_port"),
                    "protocol": flow_features.get("protocol", "tcp").lower(),
                    "description": f"Dynamic mitigation generated by Agentic RAG for {flow_features.get('src_ip')}",
                    "created_by": "rag_agent",
                }
            ],
        }

    def run_simulation(
        self,
        num_benign: int = 200,
        num_attacks: int = 150,
        num_anomalies: int = 50,
        attack_type: str = "syn_flood",
    ) -> NodeSimulationReport:
        """
        Runs an interleaved simulation of benign traffic, attack bursts, and anomalies.
        """
        benign_gen = BenignTrafficGenerator(target_ip=self.target_ip, use_scapy=False)
        attack_gen = AttackTrafficGenerator(attack_type=attack_type, target_ip=self.target_ip, use_scapy=False)
        anomaly_gen = AnomalyTrafficGenerator(target_ip=self.target_ip, use_scapy=False)

        # Build packet sequence with ground-truth labels
        stream: list[tuple[Any, bool]] = []

        for p in benign_gen.generate_batch(num_benign):
            stream.append((p, False))

        for p in attack_gen.generate_batch(num_attacks):
            stream.append((p, True))

        for p in anomaly_gen.generate_batch(num_anomalies):
            stream.append((p, True))

        # Shuffle to simulate mixed real-world arrivals
        import random
        random.shuffle(stream)

        tp, fp, tn, fn = 0, 0, 0, 0
        t0 = time.perf_counter()

        for pkt, is_attack in stream:
            decision = self.controller.process_packet(pkt)
            if decision is None:
                continue

            # Check if firewall blocked or defended
            blocked = decision.is_blocked or (decision.action == RuleAction.TRIGGER_RAG)

            if blocked and is_attack:
                tp += 1
            elif blocked and not is_attack:
                fp += 1
            elif not blocked and not is_attack:
                tn += 1
            else:
                fn += 1

        t1 = time.perf_counter()
        duration = max(0.001, t1 - t0)

        total = tp + fp + tn + fn
        accuracy = (tp + tn) / total if total > 0 else 0.0
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0

        metrics = self.controller.get_metrics()

        return NodeSimulationReport(
            node_id=self.node_id,
            total_packets=metrics.total_packets_inspected,
            allowed_count=metrics.packets_allowed,
            blocked_count=metrics.packets_blocked,
            dropped_count=metrics.packets_dropped,
            rag_triggers=metrics.rag_triggers,
            emergency_drops=metrics.emergency_drops,
            true_positives=tp,
            false_positives=fp,
            true_negatives=tn,
            false_negatives=fn,
            accuracy=accuracy,
            precision=precision,
            recall=recall,
            f1_score=f1,
            duration_seconds=duration,
            packets_per_second=total / duration,
        )

    def export_fl_weights(self, round_num: int = 1) -> dict[str, Any]:
        """
        Exports the local edge node's model weights formatted for Member 3's FL aggregation.
        """
        metrics = self.controller.get_metrics()
        total = metrics.packets_allowed + metrics.packets_blocked + metrics.packets_dropped
        acc = (metrics.packets_allowed + metrics.packets_blocked) / total if total > 0 else 0.0

        model = self.controller.classifier._rl_model or DuelingDQN()
        return CheckpointManager.export_for_federation(
            model_or_agent=model,
            round_num=round_num,
            metrics={"accuracy": acc, "f1": acc},
            node_id=self.node_id,
        )
